<?php
/**
 * Created by PhpStorm.
 * User: awt
 * Date: 11/12/2017
 * Time: 4:13 PM
 */

require_once 'Scripts.php';
if(isset($_GET['code']) && isset($_GET['id']))
    $result = $script->activate($_GET['id'],$_GET['code']);

?>

<!doctype html>
<html>
<head>
    <title>Send Email</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"  type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<?php include "nav.phtml"; ?>

<div class="container">

    <div class="panel panel-warning">
        <div class="panel-heading"><h1>Activation</h1></div>
        <div class="panel-body"><p>Your account has
            <?php if($result == 1): ?>
                Activated successfully.
            <?php else: ?>
                not been activated.
            <?php endif; ?>
        </p>
        </div>
    </div>

</div>

</body>
</html>