<?php
/**
 * Created by PhpStorm.
 * User: awt
 * Date: 11/12/2017
 * Time: 9:27 AM
 */
require_once 'Scripts.php';
$status = $script->login();
?>


<!doctype html>
<html>
<head>
    <title>Send Email</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"  type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

<?php include 'nav.phtml'; ?>


<div class="container">
    <?=$status?>
    <div class="panel panel-primary">
        <div class="panel-heading"><h1>Login</h1></div>
        <div class="panel-body">
        <?php if(!$_SESSION['user'] > 0): ?>
        <fieldset>
            <form method="post">
                <div class="form-group">
                    <input class="form-control" type="email" name="email" id="email" placeholder="me@example.com" required>
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" id="password" placeholder="password" required>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" name="login" value="Login">
                    <input class="btn btn-warning" type="submit" name="forgot" value="Forgot password?">
                </div>
            </form>
        </fieldset>
        <?php else: ?>
            You are logged in.
        <?php endif; ?>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>