<?php
/**
 * Created by PhpStorm.
 * User: awt
 * Date: 11/12/2017
 * Time: 11:20 AM
 */
require_once 'Scripts.php';
$status = $script->logout();
?>


<!doctype html>
<html>
<head>
    <title>Send Email</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"  type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<?php include "nav.phtml"; ?>

<div class="container">
    <h1>Logout</h1>
    <?=$status?>
</div>

</body>
</html>