<?php
/**
 * Created by PhpStorm.
 * User: awt
 * Date: 12/12/2017
 * Time: 11:49 AM
 */
require_once 'Scripts.php';
$emails = $script->getEmailsByUser();
date_default_timezone_set('UTC');
?>

<!doctype html>
<html>
<head>
    <title>Send Email</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"  type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

<?php include 'nav.phtml'; ?>

<div class="container">
    <?php if(!isset($_SESSION['user']))
        die("<div class='alert alert-danger'><strong>Unauthorised access!</strong> You do not have access to this page!</div>Please <a href='/tools/mailer/login.phtml'>login.</a> ");
    ?>
    <div class="panel panel-primary">
        <div class="panel-heading"><h1>My Emails</h1></div>
        <div class="panel-body">
        <table class="table table-striped">
            <tr>
                <th>Subject</th>
                <th>Time</th>
            </tr>
            <?php foreach($emails as $email): ?>
                <tr>
                    <td><a href="/tools/mailer/email.phtml?id=<?= $email['id'] ?>"><?= $email['subject'] ?></a></td>
                    <td><?= gmdate("d M Y H:i", $email['time']) ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
            <?php if(gettype($emails) == 'boolean'): ?>
            No emails
            <?php else: ?>
            Total emails: <?= count($emails); ?>
            <?php endif; ?>

        </div>
    </div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

