<?php
/**
 * Created by PhpStorm.
 * User: awt
 * Date: 06/12/2017
 * Time: 3:15 PM
 */
?>
<!doctype html>
<html>
<head>
    <title>Send Email</title>
    <meta charset="UTF-8">

    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"  type="text/css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-inverse bg-primary" style="padding: 15px;">
        <a class="navbar-brand" href="#" style="margin-top:-10px; margin-bottom: 10px;">
            <img src="./images/logo.png" alt="" height="50px;">
        </a>
        <h2>Emailer</h2>
    </nav>

</div>

<div class="container">
    <?= $content ?>
</div>

</body>
</html>